name: 'ClassifierFreeDiffRoll'
args:
    residual_channels: 512
    unconditional: False
    n_mels: ${spec.args.n_mels}
    residual_layers: 15
    dilation_base: 1
    spec_dropout: 0.2
    norm_args:
    - 0
    - 1
    - 'imagewise'    