name: 'MuseDiff'
args:
    n_instruments: 5
    residual_channels: 16
    unconditional: False
    n_mels: ${spec.args.n_mels}
    residual_layers: 30
    dilation_base: 1
    norm_args:
    - 0
    - 1
    - 'imagewise'
