gpus: 1
checkpoint_path: './outputs/2022-07-12/09-46-20/diffusion_dim=28-channels=1-l2-MAESTRO/version_1/checkpoints/last.ckpt' # will be ignored in train.py
shape:
- 640
- 88

defaults:
    - model: Unet
        
trainer:
    gpus: ${gpus}