gpus: 1
hop_length: 512
sequence_length: 327680
sampling_rate: 16000
data_root: '../../MusicDataset'
checkpoint_path: './weights/Pretrain_MAESTRO-retrain_Both-k=9.ckpt' # will be ignored in train.py

dataset:
    # -----------For generation-----------
    # num_samples: 4
    # -----------For inpainting-----------
    name: 'MAPS'
    args:
        root: ${data_root} 
        groups: 'test'
        data_type: 'MUS'
        download: False
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: 16000
        overlap: True
    num_samples: 4
        
dataloader:
    batch_size: 4
    num_workers: 8
    shuffle: False
    pin_memory: True
        
task:
    frame_threshold: 0.8        
        
trainer:
    gpus: ${gpus}
    
defaults:
    - model: ClassifierFreeDiffRoll
    - task: generation