gpus: 1
val_freq: 5
hop_length: 512
sequence_length: 327680
sampling_rate: 16000
min_midi: 21
max_midi: 108
learning_rate: 1e-5
epochs: 1000
download: False
data_root: './'
pin_memory: False

dataset:
    train:
        root: ${data_root} 
        groups: 'train'            
        download: ${download}
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: 16000    
    val:
        root: ${data_root} 
        groups: 'validation'            
        download: False
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: 16000
        
    test:
        root: ${data_root} 
        groups: 'test'            
        download: False
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: 16000
        
dataloader:
    train:
        batch_size: 16
        num_workers: 20 
        shuffle: True
        pin_memory: ${pin_memory}
    val:
        batch_size: 16
        num_workers: 8
        shuffle: False
        pin_memory: ${pin_memory}
    test:
        batch_size: 4
        num_workers: 8
        shuffle: False
        pin_memory: ${pin_memory}
        
        
trainer:
    gpus: ${gpus}
    max_epochs: ${epochs}
    check_val_every_n_epoch: ${val_freq}
    
modelcheckpoint:
    monitor: 'Train/diffusion_loss'
    filename: '{epoch:02d}e-diffusion_loss{Train/diffusion_loss:.2f}'
    save_top_k: 2
    save_last: True
    mode: "min"
    auto_insert_metric_name: False    
    


defaults:
    - spec: mel
    - model: ClassifierFreeDiffRoll
    - task: classifierfree_diffusion