gpus: 1
hop_length: 512
sequence_length: 327680
sampling_rate: 16000
data_root: '../../MusicDataset'
checkpoint_path: 'outputs/2022-12-08/16-51-43/DiscreteClassifierFreeDiffRoll-L15-C512-x_0-cfdg_ddpm_x0-w=0-p=0.1-k=3-dia=2-4-MAESTRO/version_1/checkpoints/last.ckpt' # will be ignored in train.py

# e_x0 './outputs/2022-08-19/13-10-56/DiffRoll-ddim-L15-C512-beta0.02-ex_0-dilation1-huber-MAESTRO/version_1/checkpoints/last.ckpt'
        
dataloader:
    test:
        batch_size: 16
        num_workers: 8
        shuffle: False
        pin_memory: True
        
task:
    frame_threshold: 0.5
    sampling:
        type: 'cfdg_ddpm_x0'
        w: 0.5 # 0.1 0.5 1
        
trainer:
    gpus: ${gpus}
    
defaults:
    - model: DiscreteClassifierFreeDiffRoll
    - dataset: MAESTRO