gpus: 1
hop_length: 512
sequence_length: 327680
sampling_rate: 16000
data_root: './'
checkpoint_path: './outputs/2022-08-24/11-48-06/DiffRollBaseline-L15-C512-t=constant_maxT-x_t=gaussian-MAESTRO//version_1/checkpoints/last.ckpt' # will be ignored in train.py

# e_x0 './outputs/2022-08-19/13-10-56/DiffRoll-ddim-L15-C512-beta0.02-ex_0-dilation1-huber-MAESTRO/version_1/checkpoints/last.ckpt'

dataset:
    test:
        root: ${data_root} 
        groups: 'test'            
        download: False
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: 16000
        
dataloader:
    test:
        batch_size: 16
        num_workers: 8
        shuffle: False
        pin_memory: True
        
task:
    frame_threshold: null
    sampling:
        type: null
        
trainer:
    gpus: ${gpus}
    
defaults:
    - model: ClassifierFreeDiffRoll